/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaswingdev.main;
import java.awt.Color;
import model.Bill;
import java.util.Date;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.ArrayList;
import javaswingdev.form.Message;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Product;
import org.jdesktop.animation.timing.Animator;
import org.jdesktop.animation.timing.TimingTarget;
import org.jdesktop.animation.timing.TimingTargetAdapter;
import javaswingdev.swing.table.OrderEventAction;
import model.Order;

public class Billing extends javax.swing.JFrame {
    
    private DefaultTableModel model;
    private TableRowSorter<TableModel> rowSorter;
    private final Animator animator;
    private OrderEventAction orderEventAction;
    private boolean ok;
    private boolean show = true;
    private Bill bill;
    private DefaultTableModel allBillModel;
    private javaswingdev.swing.table.Table allBillTable;

    public Bill getBill() {
        return bill;
    }
    
    public void setBill(Bill bill) {
        this.bill = bill;
    }
    
    public boolean isOk() {
        return ok;
    }

    public void setOk(boolean ok) {
        this.ok = ok;
    }

//    private final Animator animator;
//    private boolean show = true;
    
    public void showBillInfo(Bill bill, DefaultTableModel model, javaswingdev.swing.table.Table allBillTable) {
        staffName.setText(bill.getStaff().getName());
        billDate.setText(bill.getDate().toString());
        for (Order o: getBill().getOrderList()) {
                table1.addRow(o.toRowTable(orderEventAction));
            }
        billTotal.setText(Double.toString(bill.getTotalCost()));
        billPaid.setText(Double.toString(bill.getPaid()));
        billReturn.setText(Double.toString(bill.getPaid() - bill.getTotalCost()));
        allBillModel = model;
        this.allBillTable = allBillTable;
        setVisible(true);
    }
    
    public Billing(java.awt.Frame parent, boolean modal) {
        initComponents();
        table1.fixTable(jScrollPane2);
        initTable();
        centerComponent();
         getContentPane().setBackground(Color.WHITE);
        TimingTarget target = new TimingTargetAdapter() {
            @Override
            public void timingEvent(float fraction) {
                if (show) {
                    setOpacity(fraction);
                } else {
                    setOpacity(1f - fraction);
                }
            }

            @Override
            public void end() {
                if (show == false) {
                    setVisible(false);
                }
            }

        };
        animator = new Animator(200, target);
        animator.setResolution(0);
        animator.setAcceleration(0.5f);
    }
    
    private void initTable() {
        orderEventAction = new OrderEventAction() {
            Message msg=new Message();
            @Override
            public void delete(Order order) {
             if(msg.showMessage("Delete this order?")){
                 Product orderProduct = order.getProduct();
                 orderProduct.setQuantity(orderProduct.getProductId() + 1);
                bill.deleteOrder(order.getOrderId());
                billTotal.setText(Double.toString(bill.getTotalCost()));
                model =(DefaultTableModel) table1.getModel();
                model.removeRow(table1.getSelectedRow());
                msg.showDialog("Delete Order Id " + bill.getBillId()+" Successfully!","red");
             }else {
                    System.out.println("User click Cancel");
                }
            }
            
            @Override
            public void update(Order order) {
                msg.showDialog("Remove and add new to update", "red");
            }
        };
        
        table1.fixTable(jScrollPane2);
    }
    
    private void centerComponent(){
        this.setLocationRelativeTo(Dashboard.getFrames()[0]);
    }
    
    private void closeMenu() {
        if (animator.isRunning()) {
            animator.stop();
        }
        show = false;
        animator.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        billDate = new javax.swing.JLabel();
        staffNameLabel = new javax.swing.JLabel();
        staffName = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        table1 = new javaswingdev.swing.table.Table();
        quantity = new javaswingdev.raven.swing.TextField();
        jLabel4 = new javax.swing.JLabel();
        findProduct = new javaswingdev.swing.Button();
        productId = new javaswingdev.raven.swing.TextField();
        billReturn = new javaswingdev.raven.swing.TextField();
        price = new javaswingdev.raven.swing.TextField();
        billTotal = new javaswingdev.raven.swing.TextField();
        billPaid = new javaswingdev.raven.swing.TextField();
        addToBillBtn = new javaswingdev.swing.Button();
        name = new javaswingdev.raven.swing.TextField();
        okBtn3 = new javaswingdev.swing.Button();
        roundPanel1 = new javaswingdev.swing.RoundPanel();

        setBackground(new java.awt.Color(204, 204, 0));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(74, 74, 74));
        jLabel3.setText("Date:");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 20, 100, -1));

        billDate.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        billDate.setForeground(new java.awt.Color(74, 74, 74));
        getContentPane().add(billDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 20, 220, 30));

        staffNameLabel.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        staffNameLabel.setForeground(new java.awt.Color(74, 74, 74));
        staffNameLabel.setText("Staff:");
        staffNameLabel.setDoubleBuffered(true);
        staffNameLabel.setFocusTraversalPolicyProvider(true);
        getContentPane().add(staffNameLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 50, -1, -1));

        staffName.setFont(new java.awt.Font("Dialog", 0, 12)); // NOI18N
        staffName.setForeground(new java.awt.Color(74, 74, 74));
        getContentPane().add(staffName, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 50, 250, 30));

        table1.setBackground(new java.awt.Color(255, 0, 102));
        table1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Product", "Price", "Quantity", "Total", "Action"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        table1.setRowHeight(41);
        jScrollPane2.setViewportView(table1);
        if (table1.getColumnModel().getColumnCount() > 0) {
            table1.getColumnModel().getColumn(0).setMinWidth(28);
            table1.getColumnModel().getColumn(0).setPreferredWidth(28);
            table1.getColumnModel().getColumn(0).setMaxWidth(28);
            table1.getColumnModel().getColumn(3).setMinWidth(35);
            table1.getColumnModel().getColumn(3).setPreferredWidth(35);
            table1.getColumnModel().getColumn(3).setMaxWidth(35);
            table1.getColumnModel().getColumn(5).setMinWidth(85);
            table1.getColumnModel().getColumn(5).setPreferredWidth(85);
            table1.getColumnModel().getColumn(5).setMaxWidth(85);
        }

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 110, 520, 250));

        quantity.setLabelText("Quantity");
        getContentPane().add(quantity, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 280, 60));

        jLabel4.setFont(new java.awt.Font("sansserif", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(106, 106, 164));
        jLabel4.setText("Bill Info");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 30, 100, 30));

        findProduct.setForeground(new java.awt.Color(255, 255, 255));
        findProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/icons8_search_20px.png"))); // NOI18N
        findProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                findProductActionPerformed(evt);
            }
        });
        getContentPane().add(findProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, 30, 30));

        productId.setLabelText("Product Id");
        productId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productIdActionPerformed(evt);
            }
        });
        getContentPane().add(productId, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 110, 280, -1));

        billReturn.setEditable(false);
        billReturn.setLabelText("Return");
        getContentPane().add(billReturn, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 390, 270, -1));

        price.setEditable(false);
        price.setLabelText("Price");
        getContentPane().add(price, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 230, 280, 60));

        billTotal.setEditable(false);
        billTotal.setLabelText("Total");
        getContentPane().add(billTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 390, 280, -1));

        billPaid.setLabelText("Paid");
        getContentPane().add(billPaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 390, 260, -1));

        addToBillBtn.setBackground(new java.awt.Color(122, 180, 113));
        addToBillBtn.setForeground(new java.awt.Color(255, 255, 255));
        addToBillBtn.setText("ADD");
        addToBillBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addToBillBtnActionPerformed(evt);
            }
        });
        getContentPane().add(addToBillBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 350, 50, 30));

        name.setEditable(false);
        name.setLabelText("Product name");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 280, 60));

        okBtn3.setBackground(new java.awt.Color(98, 98, 157));
        okBtn3.setForeground(new java.awt.Color(255, 255, 255));
        okBtn3.setLabel("OK");
        okBtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okBtn3ActionPerformed(evt);
            }
        });
        getContentPane().add(okBtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 470, 110, 40));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        getContentPane().add(roundPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 530));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addToBillBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addToBillBtnActionPerformed
        // TODO add your handling code here:
        Message msg = new Message();
           if(productId.getText().equals("") || quantity.getText().equals("")){
               msg.showDialog("Please fill in id and quantity", "red");
           }else{
             int pid= Integer.parseInt(productId.getText());
             Product pd= Dashboard.store.getProduct(pid);
             Order order;
             if(pd != null){
                 Double pr=pd.getProductPrice();
                    int quan=Integer.parseInt(quantity.getText());
                     
                    if(quan > pd.getQuantity()){
                        msg.showDialog("Out of stock!", "red");
                    }else{
                        int orderId = bill.maxOrderId++;
                        order= new Order(orderId,pd,quan);
                        bill.addOrder(order);
                        billTotal.setText(Double.toString(bill.getTotalCost()));
                        pd.setQuantity(pd.getQuantity() - 1);
                        table1.addRow(order.toRowTable(orderEventAction));
                    }
             }else{
                 msg.showDialog("Product not found.", "red");
             }
             
           }
    }//GEN-LAST:event_addToBillBtnActionPerformed

    private void productIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productIdActionPerformed

    private void findProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_findProductActionPerformed
        // TODO add your handling code here:
        
        int pid= Integer.parseInt(productId.getText());
        Product pd= Dashboard.store.getProduct(pid);
        if(pd!=null){
            name.setText(pd.getProductName());
            price.setText(Double.toString(pd.getProductPrice()));
            

        }
    }//GEN-LAST:event_findProductActionPerformed

    private void okBtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okBtn3ActionPerformed
        // TODO add your handling code here:
        allBillModel.setValueAt(bill.getTotalCost(),allBillTable.getSelectedRow() , 3);
        setVisible(false);
    }//GEN-LAST:event_okBtn3ActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.swing.Button addToBillBtn;
    private javax.swing.JLabel billDate;
    private javaswingdev.raven.swing.TextField billPaid;
    private javaswingdev.raven.swing.TextField billReturn;
    private javaswingdev.raven.swing.TextField billTotal;
    private javaswingdev.swing.Button findProduct;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane2;
    private javaswingdev.raven.swing.TextField name;
    private javaswingdev.swing.Button okBtn3;
    private javaswingdev.raven.swing.TextField price;
    private javaswingdev.raven.swing.TextField productId;
    private javaswingdev.raven.swing.TextField quantity;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javax.swing.JLabel staffName;
    private javax.swing.JLabel staffNameLabel;
    private javaswingdev.swing.table.Table table1;
    // End of variables declaration//GEN-END:variables
}
