/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package javaswingdev.form;
import javaswingdev.main.Dashboard;
import javaswingdev.main.ProductInfo;
import javaswingdev.swing.table.ProductEventAction;
import model.*;

public class Form_Product extends javax.swing.JPanel {

    /**
     * Creates new form Form_Shift
     */
    public Form_Product() {
        initComponents();
        table.fixTable(jScrollPane1);
        initTable();
        
    }
    
    private void showUpdateForm(Product product){
        ProductInfo form = new ProductInfo(Dashboard.getFrames()[0], true);
        form.setOk(true);
        form.showInfo(product);
    }
       private void initTable() {
        ProductEventAction productEventAction = new ProductEventAction() {
            @Override
            public void delete(Product product) {
                System.out.println(product);
            }

            @Override
            public void update(Product product) {
                showUpdateForm(product);
            }
        };
        
        table.fixTable(jScrollPane1);
        table.addRow(new Product(1, "Polo Shirt", 299000, "Teelab", "Áo phông", "Ao tra da via he", 10).toRowTable(productEventAction));
        table.addRow(new Product(2, "Jacket", 350000, "H&M", "Clothes", "Áo khoác", 12).toRowTable(productEventAction));
        table.addRow(new Product(3, "Vietnam Pride", 200000, "Bò sữa", "Clothes", "Du lịch thì vô địch", 17).toRowTable(productEventAction));
        table.addRow(new Product(4, "Somi Oxford", 413000, "Routine", "Áo sơ mi", "Lịch lãm", 21).toRowTable(productEventAction));
        table.addRow(new Product(5, "Sơmi dài tay Dobby", 413000, "Routine", "Áo sơ mi", "Lịch lãm, năng động", 5).toRowTable(productEventAction));
        table.addRow(new Product(6, "Sơ mi Seersucker", 472000, "Routine", "Áo sơ mi", "Trẻ trung", 12).toRowTable(productEventAction));
        table.addRow(new Product(7, "Sơ mi caro", 299000, "Routine", "Clothes", "Ao tra da via he", 3).toRowTable(productEventAction));
        table.addRow(new Product(8, "Quần Jean trơn", 480000, "Routine", "Quần Jean", "Slimfit", 11).toRowTable(productEventAction));
        table.addRow(new Product(9, "Quần khaki V", 299000, "Routine", "Quần khaki", "Slimcrop", 10).toRowTable(productEventAction));
        table.addRow(new Product(10, "Áo phông Marvel Comics", 599000, "Boo", "Áo phông", "Boo x Marvel", 10).toRowTable(productEventAction));
        table.addRow(new Product(11, "Áo phông Hulk", 490000, "Boo", "Áo phông", "Boo x Marvel: Hulk", 10).toRowTable(productEventAction));
        table.addRow(new Product(12, "Giày Nightwatch", 4999000, "Adidas", "Giày", "Adidas x GoT", 10).toRowTable(productEventAction));
        table.addRow(new Product(13, "Bitis Hunter X 2022", 1199000, "Bitis Hunter", "Giày", "Bitis Hunter Collection", 10).toRowTable(productEventAction));
        table.addRow(new Product(14, "Bitis Hunter X 2021", 999000, "Bitis Hunter", "Giày", "Bitis Hunter Collection", 10).toRowTable(productEventAction));
        table.addRow(new Product(15, "Hà Nội Trà Đá", 189000, "Teelab", "Áo phông", "Ao tra da via he", 10).toRowTable(productEventAction));
        table.addRow(new Product(16, "Ultraboost 22", 3900000, "Adidas", "Giày", "Giày chạy thể thao", 10).toRowTable(productEventAction));
        table.addRow(new Product(17, "Ultraboost 5.0 DNA", 2990000, "Adidas", "Giày", "Giày chạy thể thao", 10).toRowTable(productEventAction));
        table.addRow(new Product(18, "Jeans Bermuda", 434000, "Boo", "Quần Jeans", "Quần regular form", 10).toRowTable(productEventAction));
  }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roundPanel1 = new javaswingdev.swing.RoundPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javaswingdev.swing.table.Table();
        textFieldAnimation1 = new swing.TextFieldAnimation();
        addProdBtn = new javaswingdev.swing.Button();

        setBackground(new java.awt.Color(243, 243, 243));

        roundPanel1.setBackground(new java.awt.Color(255, 255, 255));
        roundPanel1.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        roundPanel1.setRound(10);

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "#", "Name", "Price", "Brand", "Category", "Description", "Quantity", "Action"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table);
        if (table.getColumnModel().getColumnCount() > 0) {
            table.getColumnModel().getColumn(0).setPreferredWidth(25);
        }

        javax.swing.GroupLayout roundPanel1Layout = new javax.swing.GroupLayout(roundPanel1);
        roundPanel1.setLayout(roundPanel1Layout);
        roundPanel1Layout.setHorizontalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 788, Short.MAX_VALUE)
        );
        roundPanel1Layout.setVerticalGroup(
            roundPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(roundPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 12, Short.MAX_VALUE))
        );

        textFieldAnimation1.setForeground(new java.awt.Color(153, 153, 153));
        textFieldAnimation1.setAnimationColor(new java.awt.Color(87, 97, 174));
        textFieldAnimation1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                textFieldAnimation1FocusGained(evt);
            }
        });

        addProdBtn.setBackground(new java.awt.Color(87, 97, 174));
        addProdBtn.setForeground(new java.awt.Color(255, 255, 255));
        addProdBtn.setText("ADD ");
        addProdBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProdBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(addProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(39, 39, 39)
                        .addComponent(textFieldAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, 676, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(38, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldAnimation1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addProdBtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(37, 37, 37)
                .addComponent(roundPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addProdBtnActionPerformed(java.awt.event.ActionEvent evt) {                                           
   
//        ModelStaff newStaff= new ModelStaff();
//        
//        showUpdateStaff(newStaff);
new ProductInfo(Dashboard.getFrames()[0], true).setVisible(true);
    }
    private void textFieldAnimation1FocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_textFieldAnimation1FocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldAnimation1FocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.swing.Button addProdBtn;
    private javax.swing.JScrollPane jScrollPane1;
    private javaswingdev.swing.RoundPanel roundPanel1;
    private javaswingdev.swing.table.Table table;
    private swing.TextFieldAnimation textFieldAnimation1;
    // End of variables declaration//GEN-END:variables
}
